name: CML Notebook Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter cml

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute RFR.ipynb --output executed_RFR.ipynb

      - name: Convert to Markdown for report
        run: |
          jupyter nbconvert --to markdown executed_RFR.ipynb --output report.md

      - name: Post CML comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create report.md
