name: CML Python Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-cml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Fix distutils for Python 3.10
        run: |
          wget https://bootstrap.pypa.io/get-pip.py
          python get-pip.py --upgrade

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install CML from GitHub
        run: |
          npm install -g @dvcorg/cml

      - name: Run training script
        run: |
          python RFR.py > metrics.txt
          echo "### Model Report" > report.md
          cat metrics.txt >> report.md

      - name: Post report to PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create report.md
